# Generated by Django 2.2.6 on 2019-12-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNegative', models.BooleanField()),
                ('name', models.TextField()),
                ('cashflowdate', models.DateField()),
                ('bookingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.BookingType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.Company')),
                ('invoice', models.ManyToManyField(blank=True, to='accountx.Media')),
            ],
        ),
    ]
