# Generated by Django 2.2.8 on 2020-01-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invDate', models.DateField()),
                ('customer', models.TextField()),
                ('project', models.TextField()),
                ('ust', models.FloatField()),
                ('net', models.FloatField()),
                ('cashflowdate', models.DateField()),
                ('bookingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.BookingType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.Company')),
                ('invoice', models.ManyToManyField(blank=True, to='accountx.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invNo', models.TextField()),
                ('invDate', models.DateField()),
                ('biller', models.TextField()),
                ('ust', models.FloatField()),
                ('net', models.FloatField()),
                ('cashflowdate', models.DateField()),
                ('bookingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.BookingType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.Company')),
                ('invoice', models.ManyToManyField(blank=True, to='accountx.Media')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountx.Company'),
        ),
    ]
