# Generated by Django 2.2.8 on 2020-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bookingType',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bookingType',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='BookingType',
        ),
    ]
