# Generated by Django 2.2.8 on 2020-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
