# Generated by Django 2.2.6 on 2019-12-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='datafile',
        ),
    ]
