# Generated by Django 2.2.7 on 2019-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
