# Generated by Django 2.2.8 on 2020-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0002_auto_20200105_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cashflowdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashflowdate',
            field=models.DateField(blank=True),
        ),
    ]
