# Generated by Django 2.2.6 on 2019-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0002_remove_media_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.ManyToManyField(blank=True, to='accountx.Media'),
        ),
    ]
