# Generated by Django 2.2.8 on 2020-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0003_auto_20200107_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cashflowdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashflowdate',
            field=models.DateField(null=True),
        ),
    ]
