# Generated by Django 2.2.8 on 2020-01-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountx', '0004_auto_20200107_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='ust',
            new_name='vat',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='ust',
            new_name='vat',
        ),
    ]
